Issue#15
igordelatorre/engenharia-de-software pull request #16
Opened 2022-09-03 21:25 UTC by Henrique-Peixoto

2022-09-03 22:22 UTC, joaopfp approved these changes

2022-09-03 22:22 UTC, joaopfp commented on flipman-api/Controllers/PlayersController.cs
> +            isActive = request.isActive
Não entendi pq deixar o campo isActive, acho que não precisamos guardar usuarios inativos.

2022-09-03 22:43 UTC, joaopfp commented on flipman-api/Controllers/TransactionsController.cs
> +using Flipman.Api.Models;
Nesse Controller estamos considerando apenas os registros de transações de prizes. Mas também precisamos descontar os tokens e prizes do banco, para garantir a consistência de dados e tal. Sugiro a criação de stores que executam essa ações, dai as chamamos nos controllers para esses fins.

2022-09-03 22:44 UTC, joaopfp commented on flipman-api/Controllers/TransactionsController.cs
> +using Flipman.Api.Models;
No caso, como faremos com as demais transações? Tipo adição de tickets aos jogadores, ganho de tokens, gasto de tokens etc

2022-09-03 22:55 UTC, joaopfp commented on flipman-api/Controllers/TransactionsController.cs
> +using Flipman.Api.Models;
Sugiro a mudança de nome pra PrizeTransactionController, já que vamos ter outros controllers pra outros tipos de transação que existem no software

2022-09-04 13:08 UTC, joaopfp commented on flipman-api/Controllers/PrizesController.cs
> +  public async Task<IActionResult> UpdatePrizeAmount([FromRoute] int id, [FromBody] PutPrizeRequest request)
Acredito que aqui no Put deveria ser possível atualizar mais infos sobre o prize, tipo o nome e cost

2022-09-04 13:11 UTC, joaopfp commented on flipman-api/Controllers/PrizesController.cs
> +using Flipman.Api.Models;
Seria interessante também uma rota remove

2022-09-04 13:19 UTC, joaopfp commented on flipman-api/Controllers/TransactionsController.cs
> +  public async Task<IActionResult> GetPrizes()
Acho que esse endpoint é desnecessário pois deveríamos ter acesso aos prizes através do PrizesController

2022-09-04 13:19 UTC, joaopfp commented on flipman-api/Controllers/TransactionsController.cs
> +  public async Task<IActionResult> GetPrize([FromRoute] int id) {
Esse também

2022-09-04 17:41 UTC, igordelatorre commented on flipman-api/Controllers/PrizesController.cs
> +  public async Task<IActionResult> UpdatePrizeAmount([FromRoute] int id, [FromBody] PutPrizeRequest request)
Talvez seja bom criar uma outra rota só pra atualizar essas informações. Não sei se faz sentido atualizar a quantidade em estoque junto com o resto

2022-09-04 17:51 UTC, igordelatorre requested changes

2022-09-04 17:51 UTC, igordelatorre commented on flipman-api/Controllers/PrizesController.cs
> +      return BadRequest("AMOUNT_MUST_BE_LESS_THAN_CURRENT_AMOUNT");
Acredito que o valor do request não precisa ser menor do que o valor que está em estoque. Por exemplo, caso o administrador queira adicionar mais unidades do prêmio em estoque poderia usar essa mesma rota.

Mas talvez seja interessante fazer rotas diferentes para retirar premios e para atualizar a quantidade em estoque dos premios. Então, essa rota seria a `/prizes/decrement-amount` (algo nesse sentido) e teria outra `/prizes/increment-amount`

2022-09-07 14:22 UTC, Henrique-Peixoto commented on flipman-api/Controllers/TransactionsController.cs
> +using Flipman.Api.Models;
@joaopfp, com *stores* tu quer dizer algo como *stored procedures*? Tem alguma referência ou exemplo?

2022-09-07 14:30 UTC, Henrique-Peixoto commented on flipman-api/Controllers/PrizesController.cs
> +  public async Task<IActionResult> UpdatePrizeAmount([FromRoute] int id, [FromBody] PutPrizeRequest request)
O caso de uso UC02 subseção *Remover Item* prevê somente a alteração da quantidade de um item. Mas entendo que é mais adequado poder atualizar os outros dados dos itens. Por simplicidade, vou colocar todas as alterações na mesma rota. Se houver outra sugestão, eu mudo aqui.

2022-09-07 14:35 UTC, Henrique-Peixoto commented on flipman-api/Controllers/PrizesController.cs
> +using Flipman.Api.Models;
A única exclusão de prêmios prevista nos casos de uso, é a subtração da quantidade total disponível em estoque.

2022-09-07 15:07 UTC, Henrique-Peixoto commented on flipman-api/Controllers/PrizesController.cs
> +      return BadRequest("AMOUNT_MUST_BE_LESS_THAN_CURRENT_AMOUNT");
Vou considerar a mesma rota para as duas operações. No front, (supondo) que será exibida a quantidade de um determinado prêmio, um funcionário decrementa ou incrementa a quantidade do prêmio. Baseado na nova quantidade, podemos atualizar a quantidade do prêmio no banco.

2022-09-07 15:10 UTC, Henrique-Peixoto commented on flipman-api/Controllers/TransactionsController.cs
> +  public async Task<IActionResult> GetPrizes()
Dentro da página de troca de tickets por prêmios também precisamos ter acesso aos prêmios. Então, vou só chamar o método do controller PrizesController que faz isso.

2022-09-07 17:08 UTC, igordelatorre approved these changes

2022-09-07 17:08 UTC, merged