Issue#39
igordelatorre/engenharia-de-software pull request #40
Opened 2022-09-20 19:19 UTC by Henrique-Peixoto

#39

2022-09-23 02:07 UTC, igordelatorre requested changes

2022-09-23 02:07 UTC, igordelatorre commented on flipman-api/Flipman.Api/Program.cs
> +            options.AddPolicy(AppPolicies.Match, policy => policy.RequireAuthenticatedUser().RequireClaim(AppClaims.MatchId));
O policy é uma política de autorização e aqui a gente diz quais requisitos devem ser cumpridos para ter acesso aos privilégios dessa política. Uma partida não vai acessar o sistema, então não precisa criar uma policy

2022-09-23 02:45 UTC, igordelatorre commented on flipman-api/Flipman.Api/Models/Match.cs
> +    public int Points { get; set; }
criar um atributo para quantidade de tickets que o jogador ganhou na partida

2022-09-23 03:37 UTC, igordelatorre requested changes

2022-09-23 03:37 UTC, igordelatorre commented on flipman-api/Flipman.Api.Setup/AppDbContext.cs
> +
colocar esse model no outro DbContext também. 

O DbContext do `Flipman.Api.Setup` serve pra criar as instâncias no banco mais facilmente, ele é usado apenas pra setar o ambiente de desenvolvimento. As controllers recebem o DbContext do `Flipman.Api/Models /FlipmanDbContext.cs`, por isso que é preciso colocar a model lá também. Daria pra fazer melhor do que duplicar, mas isso já quebra o galho hehe

2022-09-24 00:18 UTC, Henrique-Peixoto commented on flipman-api/Flipman.Api/Models/Match.cs
> +    public int Points { get; set; }
Acabei colocando também um atributo para a quantidade de fichas (tokens) pagos para jogar na máquina.

2022-09-24 00:24 UTC, closed without merging